#!/bin/bash
ETCFILE=/etc/passwd
if [ ! -f $ETCFILE ]
then 
 echo "file $ETCFILE not exit"
 exit 1
 fi
 while IFS : read -r username password userid groupid userfullname homeaddress shell
 do 
 echo "username is $username"
 echo "password is $password "
 echo "userid is $userid groupid is $groupid"
 done <<< ETCFILE