#!/bin/bash
FILE="/etc/passwd"
if [ ! -f $FILE ]
then 
 echo "file $FILE not exit"
 exit 1
 fi
 while IFS=":" read -r username password userid groupid userfullname homeaddress shell
 do 
 echo "username is $username "
 echo "password is $password "
 echo "userid is $userid "
 echo "groupid is $groupid"
 done < $FILE